name: tekartik_cmd_echo
description: A sample command-line application.
version: 0.2.1+1
homepage: https://github.com/tekartik/cmd_echo.dart

publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.7'
  args: any
  pub_semver: any
  path: any
  process_run: '>=0.10.9-dev.1'

dev_dependencies:
  dev_test: any
  test: ">=1.0.0"
